name = "MATLAB"
grammar = "matlab"
path_suffixes = ["m"]
line_comments = ["%"]
autoclose_before = "\"]})'"
brackets = [
    { start = "{", end = "}", close = true, newline = false },
    { start = "[", end = "]", close = true, newline = false },
    { start = "(", end = ")", close = true, newline = false },
    { start = "\"", end = "\"", close = true, newline = false },
    { start = "}'", end = "}'", close = false, newline = false }, # the next 4 lines: char string should autoclose BUT NOT if closing parenthesis, bracket etc is proceeding
    { start = ")'", end = ")'", close = false, newline = false },
    { start = "]'", end = "]'", close = false, newline = false },
    { start = "'", end = "'", close = true, newline = false },
]
